services:
  threat-intel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    restart: unless-stopped
    environment:
      - MONGODB_URI
  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ SERVICE_USER_MONGODB }
      MONGO_INITDB_ROOT_PASSWORD: ${ SERVICE_PASSWORD_64_MONGODB }
      MONGO_INITDB_DATABASE: ${ THREAT_INTEL_DB_NAME }